-- MySQL Script generated by MySQL Workbench
-- mar 08 may 2018 17:03:07 CDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db-despegaPOS
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db-despegaPOS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db-despegaPOS` DEFAULT CHARACTER SET utf8 ;
USE `db-despegaPOS` ;

-- -----------------------------------------------------
-- Table `db-despegaPOS`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-despegaPOS`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(100) NOT NULL,
  `apellidos` VARCHAR(100) NOT NULL,
  `cedula` VARCHAR(100) NULL,
  `telefono` VARCHAR(100) NULL,
  `correo` VARCHAR(100) NULL,
  `direccion` VARCHAR(150) NULL,
  `cargo` ENUM('0', '1') NOT NULL,
  `usuario` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `password2` VARCHAR(100) NOT NULL,
  `fecha_ingreso` DATE NULL,
  `estado` ENUM('0', '1') NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-despegaPOS`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-despegaPOS`.`categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(45) NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_categoria`),
  INDEX `fk_categoria_usuarios_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_categoria_usuarios`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `db-despegaPOS`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-despegaPOS`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-despegaPOS`.`producto` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `i_categoria` INT NOT NULL,
  `producto` VARCHAR(100) NOT NULL,
  `presentacion` VARCHAR(200) NOT NULL,
  `unidad` VARCHAR(45) NULL,
  `moneda` VARCHAR(45) NOT NULL,
  `precio_compra` VARCHAR(45) NULL,
  `precio_venta` VARCHAR(45) NOT NULL,
  `stock` VARCHAR(45) NOT NULL,
  `estado` ENUM('0', '1') NULL,
  `imagen` VARCHAR(100) NULL,
  `fecha_vencimiento` DATE NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `fk_producto_categoria_idx` (`i_categoria` ASC),
  INDEX `fk_producto_usuario_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_producto_categoria`
    FOREIGN KEY (`i_categoria`)
    REFERENCES `db-despegaPOS`.`categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `db-despegaPOS`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-despegaPOS`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-despegaPOS`.`proveedor` (
  `id_proveedor` INT NOT NULL AUTO_INCREMENT,
  `cedula` VARCHAR(45) NULL,
  `razon_social` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `direccion` VARCHAR(200) NULL,
  `fecha` DATE NOT NULL,
  `estado` ENUM('0', '1') NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_proveedor`),
  INDEX `fk_proveedor_usuarios_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_proveedor_usuarios`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `db-despegaPOS`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-despegaPOS`.`compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-despegaPOS`.`compras` (
  `id_compras` INT NOT NULL AUTO_INCREMENT,
  `fecha_compra` DATE NOT NULL,
  `numero_compra` VARCHAR(100) NULL,
  `proveedor` VARCHAR(100) NOT NULL,
  `cedula_proveedor` VARCHAR(100) NULL,
  `comprador` VARCHAR(100) NOT NULL,
  `moneda` VARCHAR(45) NULL,
  `subtotal` VARCHAR(100) NULL,
  `total_iva` VARCHAR(100) NULL,
  `total` VARCHAR(45) NOT NULL,
  `tipo_pago` VARCHAR(100) NOT NULL,
  `estado` ENUM('0', '1') NOT NULL,
  `id_usuario` INT NOT NULL,
  `id_proveedor` INT NOT NULL,
  PRIMARY KEY (`id_compras`),
  INDEX `fk_compras_usuarios_idx` (`id_usuario` ASC),
  INDEX `fk_compras_proveedor_idx` (`id_proveedor` ASC),
  CONSTRAINT `fk_compras_usuarios`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `db-despegaPOS`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compras_proveedor`
    FOREIGN KEY (`id_proveedor`)
    REFERENCES `db-despegaPOS`.`proveedor` (`id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-despegaPOS`.`detalle_compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-despegaPOS`.`detalle_compras` (
  `id_detalle_compras` INT NOT NULL AUTO_INCREMENT,
  `numero_compra` VARCHAR(100) NOT NULL,
  `cedula_proveedor` VARCHAR(100) NULL,
  `id_producto` INT NOT NULL,
  `moneda` VARCHAR(45) NULL,
  `precio_compra` VARCHAR(45) NOT NULL,
  `cantidad_compra` VARCHAR(45) NOT NULL,
  `descuento` VARCHAR(45) NOT NULL,
  `importe` VARCHAR(45) NOT NULL,
  `fecha_compra` DATE NOT NULL,
  `id_usuario` INT NOT NULL,
  `id_proveedor` INT NOT NULL,
  `estado` ENUM('0', '1') NOT NULL,
  `id_categoria` INT NOT NULL,
  `producto` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_detalle_compras`),
  INDEX `fk_detalle_compras_usuarios_idx` (`id_usuario` ASC),
  INDEX `fk_detalle_compras_producto_idx` (`id_producto` ASC),
  INDEX `fk_detalle_compras_proveedor_idx` (`id_proveedor` ASC),
  INDEX `fk_detalle_compras_categoria_idx` (`id_categoria` ASC),
  CONSTRAINT `fk_detalle_compras_usuarios`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `db-despegaPOS`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_compras_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `db-despegaPOS`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_compras_proveedor`
    FOREIGN KEY (`id_proveedor`)
    REFERENCES `db-despegaPOS`.`proveedor` (`id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_compras_categoria`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `db-despegaPOS`.`categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-despegaPOS`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-despegaPOS`.`clientes` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `cedula_cliente` VARCHAR(45) NULL,
  `nombre_cliente` VARCHAR(100) NOT NULL,
  `apellido_cliente` VARCHAR(100) NOT NULL,
  `telefono_cliente` VARCHAR(80) NOT NULL,
  `correo_cliente` VARCHAR(100) NULL,
  `direccion_cliente` VARCHAR(200) NULL,
  `fecha_ingreso` DATE NOT NULL,
  `estado` ENUM('0', '1') NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_cliente`),
  INDEX `fk_clientes_usuarios_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_clientes_usuarios`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `db-despegaPOS`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-despegaPOS`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-despegaPOS`.`ventas` (
  `id_ventas` INT NOT NULL AUTO_INCREMENT,
  `fecha_venta` DATE NOT NULL,
  `numero_venta` VARCHAR(45) NULL,
  `cliente` VARCHAR(100) NOT NULL,
  `cedula_cliente` VARCHAR(45) NULL,
  `vendedor` VARCHAR(45) NOT NULL,
  `moneda` VARCHAR(45) NULL,
  `subtotal` VARCHAR(45) NULL,
  `total_iva` VARCHAR(45) NULL,
  `total` VARCHAR(45) NOT NULL,
  `tipo_pago` VARCHAR(45) NOT NULL,
  `estado` ENUM('0', '1', '2') NOT NULL,
  `id_usuario` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_ventas`),
  INDEX `fk_ventas_usuarios_idx` (`id_usuario` ASC),
  INDEX `fk_ventas_clientes_idx` (`id_cliente` ASC),
  CONSTRAINT `fk_ventas_usuarios`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `db-despegaPOS`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventas_clientes`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `db-despegaPOS`.`clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-despegaPOS`.`detalle_ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-despegaPOS`.`detalle_ventas` (
  `id_detalle_ventas` INT NOT NULL AUTO_INCREMENT,
  `numero_venta` VARCHAR(45) NOT NULL,
  `cedula_cliente` VARCHAR(45) NULL,
  `id_producto` INT NOT NULL,
  `producto` VARCHAR(100) NOT NULL,
  `moneda` VARCHAR(20) NULL,
  `precio_venta` VARCHAR(20) NOT NULL,
  `cantidad_venta` VARCHAR(45) NOT NULL,
  `descuento` VARCHAR(20) NOT NULL,
  `importe` VARCHAR(45) NOT NULL,
  `fecha_venta` DATE NOT NULL,
  `id_usuario` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  `estado` ENUM('0', '1', '2') NOT NULL,
  PRIMARY KEY (`id_detalle_ventas`),
  INDEX `fk_detalle_ventas_producto_idx` (`id_producto` ASC),
  INDEX `fk_detalle_ventas_clientes_idx` (`id_cliente` ASC),
  INDEX `fk_detalle_ventas_usuarios_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_detalle_ventas_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `db-despegaPOS`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_ventas_clientes`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `db-despegaPOS`.`clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_ventas_usuarios`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `db-despegaPOS`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-despegaPOS`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-despegaPOS`.`empresa` (
  `id_empresa` INT NOT NULL AUTO_INCREMENT,
  `cedula_empresa` VARCHAR(45) NOT NULL,
  `nombre_empresa` VARCHAR(100) NOT NULL,
  `direccion_empresa` VARCHAR(200) NOT NULL,
  `correo_empresa` VARCHAR(100) NOT NULL,
  `telefono_empresa` VARCHAR(45) NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_empresa`),
  INDEX `fk_empresa_usuarios_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_empresa_usuarios`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `db-despegaPOS`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-despegaPOS`.`permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-despegaPOS`.`permisos` (
  `id_permiso` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_permiso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-despegaPOS`.`usuario_permiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-despegaPOS`.`usuario_permiso` (
  `id_usuario_permiso` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_permiso` INT NOT NULL,
  PRIMARY KEY (`id_usuario_permiso`),
  INDEX `fk_usuario_permiso_usuario_idx` (`id_usuario` ASC),
  INDEX `fk_usuario_permiso_permiso_idx` (`id_permiso` ASC),
  CONSTRAINT `fk_usuario_permiso_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `db-despegaPOS`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_permiso_permiso`
    FOREIGN KEY (`id_permiso`)
    REFERENCES `db-despegaPOS`.`permisos` (`id_permiso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
